const allUmkm = [
  { id:1, name:'Sari Rasa', icon:'building-store', category:'Kuliner', city:'Yogyakarta', productsCount:3, rating:4.8, year:2020, desc:'Sari Rasa adalah UMKM yang berfokus pada produksi abon sapi dan dendeng khas Yogyakarta. Berdiri sejak 2020, kami menggunakan daging sapi pilihan dengan resep tradisional warisan keluarga. Semua produk kami diproses secara higienis tanpa bahan pengawet buatan.', phone:'+62 812 3456 7890', email:'sari.rasa@email.com', address:'Jl. Kaliurang KM 7, Sleman, Yogyakarta 55283', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-primary to-primary-container' },
  { id:2, name:'Dapur Nita', icon:'building-store', category:'Kuliner', city:'Yogyakarta', productsCount:4, rating:4.7, year:2021, desc:'Dapur Nita memproduksi aneka camilan tradisional dan modern. Berawal dari hobi memasak, kini kami melayani pesanan dari berbagai kota di Indonesia.', phone:'+62 811 1111 1111', email:'dapur.nita@email.com', address:'Jl. Seturan Raya No. 12, Sleman, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-amber-500 to-orange-500' },
  { id:3, name:'Madu Nusantara', icon:'building-store', category:'Kuliner', city:'Yogyakarta', productsCount:2, rating:4.8, year:2022, desc:'Madu Nusantara menyediakan madu murni dan sirup buah asli dari berbagai daerah di Indonesia. Kami bekerja sama dengan petani lokal untuk mendapatkan bahan baku terbaik.', phone:'+62 812 3456 7895', email:'madu.nusantara@email.com', address:'Jl. Magelang KM 5, Sleman, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-rose-500 to-red-500' },
  { id:4, name:'Bu Sri', icon:'building-store', category:'Kuliner', city:'Yogyakarta', productsCount:1, rating:4.6, year:2019, desc:'Bu Sri adalah pelopor keripik tempe dan rempeyek di Yogyakarta. Dengan resep keluarga yang sudah ada sejak 2019, kami menjamin cita rasa autentik.', phone:'+62 812 2222 2222', email:'bu.sri@email.com', address:'Jl. Bantul KM 3, Bantul, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-amber-600 to-orange-600' },
  { id:5, name:'Bu Tatik', icon:'building-store', category:'Kuliner', city:'Yogyakarta', productsCount:1, rating:4.5, year:2021, desc:'Bu Tatik dikenal dengan bakpia pathok dan aneka kue tradisional Yogyakarta. Kami menggunakan bahan-bahan alami tanpa pengawet.', phone:'+62 813 3333 3333', email:'bu.tatik@email.com', address:'Jl. Pathok KM 2, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-yellow-600 to-amber-600' },
  { id:8, name:'Batik Lestari', icon:'shirt', category:'Fashion', city:'Solo', productsCount:5, rating:4.9, year:2024, desc:'Batik Lestari memproduksi batik tulis dan cap berkualitas tinggi dengan motif tradisional dan kontemporer. Kami melestarikan budaya batik Indonesia melalui karya-karya terbaik.', phone:'+62 812 3456 7891', email:'batik.lestari@email.com', address:'Jl. Slamet Riyadi No. 45, Solo, Jawa Tengah', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-purple-500 to-pink-500' },
  { id:9, name:'Tenun Flores', icon:'shirt', category:'Fashion', city:'Bandung', productsCount:1, rating:4.7, year:2024, desc:'Tenun Flores menghadirkan tenun ikat asli NTT dengan motif khas Flores. Setiap kain ditenun secara tradisional oleh perajin berpengalaman.', phone:'+62 812 3456 7894', email:'tenun.flores@email.com', address:'Jl. Cihampelas No. 88, Bandung, Jawa Barat', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-violet-500 to-purple-500' },
  { id:10, name:'Bu Rina', icon:'shirt', category:'Fashion', city:'Yogyakarta', productsCount:2, rating:4.6, year:2022, desc:'Bu Rina adalah butik fashion yang mengkhususkan diri pada kebaya modern dan busana wanita. Kami memadukan tradisi dengan gaya kontemporer.', phone:'+62 816 6666 6666', email:'bu.rina@email.com', address:'Jl. Taman Siswa No. 10, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-pink-500 to-rose-500' },
  { id:11, name:'Karya Tangan', icon:'brush', category:'Kerajinan', city:'Bandung', productsCount:7, rating:4.7, year:2025, desc:'Karya Tangan mengkhususkan diri pada kerajinan anyaman bambu dan rotan modern untuk dekorasi rumah dan hadiah. Setiap produk dibuat dengan keterampilan tangan yang teliti.', phone:'+62 812 3456 7892', email:'karya.tangan@email.com', address:'Jl. Dipatiukur No. 22, Bandung, Jawa Barat', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-amber-500 to-orange-500' },
  { id:12, name:'Art Shoes', icon:'shirt', category:'Fashion', city:'Yogyakarta', productsCount:1, rating:4.5, year:2023, desc:'Art Shoes adalah brand sepatu kanvas lukis tangan dengan desain unik. Setiap pasang sepatu adalah karya seni yang tidak ada duanya.', phone:'+62 817 7777 7777', email:'art.shoes@email.com', address:'Jl. Kaliurang KM 8, Sleman, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-sky-500 to-blue-500' },
  { id:13, name:'Wisnu Craft', icon:'brush', category:'Kerajinan', city:'Bali', productsCount:1, rating:4.7, year:2020, desc:'Wisnu Craft memproduksi kerajinan tangan khas Bali. Dari gelang tridatu hingga gantungan kunci ukir, setiap produk dibuat dengan penuh dedikasi.', phone:'+62 818 8888 8888', email:'wisnu.craft@email.com', address:'Jl. Raya Ubud No. 15, Gianyar, Bali', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-teal-500 to-emerald-500' },
  { id:14, name:'Mebel Jepara', icon:'brush', category:'Kerajinan', city:'Yogyakarta', productsCount:3, rating:4.8, year:2024, desc:'Mebel Jepara menghadirkan furniture kayu jati berkualitas dengan ukiran khas Jepara. Kombinasi keahlian tradisional dan desain modern.', phone:'+62 812 3456 7896', email:'mebel.jepara@email.com', address:'Jl. Bantul KM 8, Bantul, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-amber-600 to-orange-600' },
  { id:15, name:'Lusi Craft', icon:'brush', category:'Kerajinan', city:'Bandung', productsCount:1, rating:4.5, year:2023, desc:'Lusi Craft mengkhususkan diri pada boneka rajut dan kerajinan keramik. Produk kami cocok untuk hadiah anak-anak dan dekorasi rumah.', phone:'+62 819 9999 9999', email:'lusi.craft@email.com', address:'Jl. Setiabudi No. 55, Bandung, Jawa Barat', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-fuchsia-500 to-pink-500' },
  { id:16, name:'Tani Makmur', icon:'seedling', category:'Pertanian', city:'Sleman', productsCount:7, rating:4.6, year:2025, desc:'Tani Makmur adalah kelompok petani organik yang menyediakan beras merah, sayuran segar, kopi, dan hasil bumi berkualitas. Kami bertani secara alami tanpa pestisida kimia.', phone:'+62 812 3456 7893', email:'tani.makmur@email.com', address:'Jl. Kaliurang KM 12, Sleman, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-green-500 to-emerald-500' },
  { id:17, name:'Bu Tani', icon:'seedling', category:'Pertanian', city:'Sleman', productsCount:3, rating:4.5, year:2022, desc:'Bu Tani menyediakan aneka bumbu dapur segar dan olahan hasil bumi. Kami memastikan setiap produk dipanen pada saat terbaik.', phone:'+62 810 0000 0001', email:'bu.tani@email.com', address:'Jl. Pakem KM 5, Sleman, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-lime-500 to-green-500' },
  { id:18, name:'Servis Teknik', icon:'wrench', category:'Jasa', city:'Jakarta', productsCount:1, rating:4.5, year:2026, desc:'Servis Teknik menyediakan jasa perbaikan AC, HP, dan elektronik rumah tangga. Dengan teknisi berpengalaman, kami memberikan pelayanan terbaik.', phone:'+62 812 3456 7897', email:'servis.teknik@email.com', address:'Jl. Mangga Dua Raya No. 5, Jakarta Pusat', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-blue-500 to-cyan-500' },
  { id:19, name:'Bersih Bersih', icon:'wrench', category:'Jasa', city:'Jakarta', productsCount:2, rating:4.4, year:2026, desc:'Bersih Bersih adalah penyedia jasa kebersihan rumah, laundry, dan sewa alat pesta. Kami siap membantu menjaga kebersihan rumah dan acara Anda.', phone:'+62 812 3456 7898', email:'bersih.bersih@email.com', address:'Jl. Kelapa Gading Blok A No. 8, Jakarta Utara', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-sky-500 to-blue-500' },
  { id:20, name:'Digital Creative', icon:'wrench', category:'Jasa', city:'Bandung', productsCount:4, rating:4.6, year:2023, desc:'Digital Creative adalah studio kreatif yang menyediakan jasa desain grafis, fotografi produk, video editing, dan pembuatan website untuk UMKM.', phone:'+62 812 3456 7899', email:'digital.creative@email.com', address:'Jl. Dago No. 33, Bandung, Jawa Barat', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-indigo-500 to-blue-500' },
  { id:21, name:'Edukita', icon:'wrench', category:'Jasa', city:'Yogyakarta', productsCount:2, rating:4.3, year:2024, desc:'Edukita adalah lembaga bimbingan belajar yang menyediakan les privat matematika, bahasa Inggris, dan jasa pengetikan untuk pelajar dan mahasiswa.', phone:'+62 810 0000 0002', email:'edukita@email.com', address:'Jl. Demangan Baru No. 3, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-cyan-500 to-teal-500' },
  { id:22, name:'Beauty Queen', icon:'sparkles', category:'Kosmetik', city:'Yogyakarta', productsCount:4, rating:4.7, year:2025, desc:'Beauty Queen adalah salon kecantikan sekaligus produsen kosmetik berkualitas. Kami menyediakan layanan make up, potong rambut, dan produk kecantikan.', phone:'+62 810 0000 0003', email:'beauty.queen@email.com', address:'Jl. Gejayan No. 15, Sleman, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-pink-500 to-rose-500' },
  { id:23, name:'Sehati', icon:'wrench', category:'Jasa', city:'Yogyakarta', productsCount:1, rating:4.4, year:2024, desc:'Sehati menyediakan jasa pijat tradisional dan minyak urat herbal. Terapis kami berpengalaman dan telah tersertifikasi.', phone:'+62 810 0000 0006', email:'sehati@email.com', address:'Jl. Wirobrajan No. 7, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-red-500 to-rose-500' },
  { id:24, name:'Wisata Kita', icon:'wrench', category:'Jasa', city:'Yogyakarta', productsCount:1, rating:4.5, year:2023, desc:'Wisata Kita menyediakan jasa tour guide profesional untuk wisata di Yogyakarta dan sekitarnya. Nikmati pengalaman wisata yang berkesan.', phone:'+62 810 0000 0007', email:'wisata.kita@email.com', address:'Jl. Malioboro No. 55, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-emerald-500 to-teal-500' },
  { id:25, name:'Glowing Skin', icon:'sparkles', category:'Kosmetik', city:'Bandung', productsCount:5, rating:4.6, year:2025, desc:'Glowing Skin adalah brand perawatan kulit organik dari bahan alami Indonesia. Kami memproduksi serum, masker, VCO, dan sunscreen berkualitas.', phone:'+62 810 0000 0004', email:'glowing.skin@email.com', address:'Jl. Riau No. 77, Bandung, Jawa Barat', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-fuchsia-500 to-pink-500' },
  { id:26, name:'Herbal Indo', icon:'sparkles', category:'Kosmetik', city:'Yogyakarta', productsCount:2, rating:4.5, year:2026, desc:'Herbal Indo memproduksi kosmetik dan perawatan tubuh herbal alami. Sabun, lip balm, dan deodoran kami dibuat dari bahan-bahan tradisional Indonesia.', phone:'+62 810 0000 0005', email:'herbal.indo@email.com', address:'Jl. Timoho No. 22, Yogyakarta', social:{instagram:'#',tiktok:'#',youtube:'#'}, coverGradient:'from-rose-500 to-pink-500' },
];

const iconMap = { 'Kuliner':'building-store','Fashion':'shirt','Kerajinan':'brush','Pertanian':'seedling','Jasa':'wrench','Kosmetik':'sparkles' };

function getUmkmById(id) {
  return allUmkm.find(u => u.id === id);
}

function getProductsByUmkmId(umkmId) {
  return allProducts.filter(p => p.umkmId === umkmId);
}
